#ifndef LIBQT6ROCKCHIP_H
#define LIBQT6ROCKCHIP_H
#include <QtCore/qglobal.h>
#if defined(QTROCKCHIP_QT6BLUETOOTH_LIBRARY)
#define QTROCKCHIP_QT6BLUETOOTH_EXPORT Q_DECL_EXPORT
#else
#define QTROCKCHIP_QT6BLUETOOTH_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQT6ROCKCHIP_H
