#ifndef LIBQT6ROCKCHIP_H
#define LIBQT6ROCKCHIP_H
#include <QtCore/qglobal.h>
#if defined(QT6ROCKCHIP_BLUETOOTH_LIBRARY)
#define QT6ROCKCHIP_BLUETOOTH_EXPORT Q_DECL_EXPORT
#else
#define QT6ROCKCHIP_BLUETOOTH_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQT6ROCKCHIP_H
